In [19]:
import numpy as np
arr1=np.array([1,7,8,9,4])
arr2=np.array([4,5,6,4,5])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1**arr2)
print(arr1/arr2)
print(np.sqrt(arr1))
print(np.sqrt(arr2))

[ 5 12 14 13  9]
[-3  2  2  5 -1]
[ 4 35 48 36 20]
[     1  16807 262144   6561   1024]
[0.25       1.4        1.33333333 2.25       0.8       ]
[1.         2.64575131 2.82842712 3.         2.        ]
[2.         2.23606798 2.44948974 2.         2.23606798]


In [29]:
arr2=np.array([[20,40,60],[180,100,120]])
print(arr2)
print(arr2[1,2])
print(arr2[0,2])
print(arr2[0,0])
print(arr2[1,1])
print(arr2[1,:])
print(arr2[:,2])

[[ 20  40  60]
 [180 100 120]]
120
60
20
100
[180 100 120]
[ 60 120]


In [33]:
arr2=np.array([[20,40,60],[180,100,120]])
print(arr2.shape)
print(arr2.ndim)
print(arr2.dtype)
print(arr2.itemsize)
print(arr2.size)

(2, 3)
2
int32
4
6


In [35]:
arr2=np.array([[20,40,60],[180,100,120]])
print(arr2.sum())
print(arr2.sum(axis=0))
print(arr2.sum(axis=1))
print(arr2.min())
print(arr2.max())
print(arr2.mean())
print(arr2.std())



520
[200 140 180]
[120 400]
20
180
86.66666666666667
53.748384988656994


In [43]:
np.zeros((2,3))
np.ones((3,3))
np.eye(3)
np.full((2,2),7)
np.arange(0,10,2)
np.linspace(0,1,5)
np.random.rand(2,3)
np.random.randint(1,10,(2,3))


array([[4, 3, 5],
       [4, 3, 8]])

In [49]:
a=np.array([1,2,3,4,5])
for index_value, value in enumerate(a):
       print(f'this is index value{index_value} and value of data{value}')

this is index value0 and value of data1
this is index value1 and value of data2
this is index value2 and value of data3
this is index value3 and value of data4
this is index value4 and value of data5


In [55]:
#monthly tracker
#minor project
expense=np.array([1000,2500,4000,5600,3250])
category=np.array(['medical','grocery','clothes','rent','education'])
print(expense)
print(category)
print(expense.min())
print(expense.max())
print(expense.sum())
print(expense.mean())

[1000 2500 4000 5600 3250]
['medical' 'grocery' 'clothes' 'rent' 'education']
1000
5600
16350
3270.0
